 
    '------------------------------------------------------------------------------
    ' <auto-generated>
    '     This code was generated by a tool.
    '
    '     Changes to this file may cause incorrect behavior and will be lost if
    '     the code is regenerated. 
    ' </auto-generated>
    '------------------------------------------------------------------------------

Option Strict On
Option Explicit On

    Namespace Pages.Tests.MBTI.UserControls
    Partial Public Class SelectIE

        '''<summary>
        '''rbE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbE As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbI control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbI As Global.System.Web.UI.WebControls.RadioButton
    End Class

    End Namespace