'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages.Tests.MBTI.UserControls
    
    Partial Public Class Step01
        
        '''<summary>
        '''ddlYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlYear As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMonth As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDay As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''rbMan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbMan As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''rbWoman control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbWoman As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''rbSingle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbSingle As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''rbMaried control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbMaried As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''ddlGraduation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGraduation As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
