'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages.Tests.MBTI

    Partial Public Class Test

        '''<summary>
        '''Wizard1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Wizard1 As Global.System.Web.UI.WebControls.Wizard

        '''<summary>
        '''WizardStep1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WizardStep1 As Global.System.Web.UI.WebControls.WizardStep

        '''<summary>
        '''Step01_1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Step01_1 As Global.IranZehn.Pages.Tests.MBTI.UserControls.Step01

        '''<summary>
        '''WizardStep2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WizardStep2 As Global.System.Web.UI.WebControls.WizardStep

        '''<summary>
        '''Step02_1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Step02_1 As Global.IranZehn.Pages.Tests.MBTI.UserControls.Step02

        '''<summary>
        '''WizardStep3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WizardStep3 As Global.System.Web.UI.WebControls.WizardStep

        '''<summary>
        '''SelectIE1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectIE1 As Global.IranZehn.Pages.Tests.MBTI.UserControls.SelectIE

        '''<summary>
        '''WizardStep4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WizardStep4 As Global.System.Web.UI.WebControls.WizardStep

        '''<summary>
        '''SelectSN1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectSN1 As Global.IranZehn.Pages.Tests.MBTI.UserControls.SelectSN

        '''<summary>
        '''WizardStep5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WizardStep5 As Global.System.Web.UI.WebControls.WizardStep

        '''<summary>
        '''SelectFT1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectFT1 As Global.IranZehn.Pages.Tests.MBTI.UserControls.SelectFT

        '''<summary>
        '''WizardStep6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WizardStep6 As Global.System.Web.UI.WebControls.WizardStep

        '''<summary>
        '''SelectPJ1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectPJ1 As Global.IranZehn.Pages.Tests.MBTI.UserControls.SelectPJ
    End Class
End Namespace
